//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminForOnlineShoppingApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MiniProject_ShopEntities : DbContext
    {
        public MiniProject_ShopEntities()
            : base("name=MiniProject_ShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Retailer> Retailers { get; set; }
        public virtual DbSet<Update_Products> Update_Products { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Wishlist> Wishlists { get; set; }
    
        public virtual int ApproveProductStatus(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ApproveProductStatus", idParameter);
        }
    
        public virtual int ApproveRetailerStatus(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ApproveRetailerStatus", idParameter);
        }
    
        public virtual int ChangeProductPrice(Nullable<int> id, Nullable<decimal> pr)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var prParameter = pr.HasValue ?
                new ObjectParameter("pr", pr) :
                new ObjectParameter("pr", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeProductPrice", idParameter, prParameter);
        }
    
        public virtual int ChangeProductQuantity(Nullable<int> id, Nullable<int> qu)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var quParameter = qu.HasValue ?
                new ObjectParameter("qu", qu) :
                new ObjectParameter("qu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeProductQuantity", idParameter, quParameter);
        }
    
        public virtual int DeleteProduct(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProduct", idParameter);
        }
    
        public virtual int DeleteRetailers(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteRetailers", idParameter);
        }
    
        public virtual int RevokeRetailerStatus(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RevokeRetailerStatus", idParameter);
        }
    
        public virtual ObjectResult<ViewProducts_Result> ViewProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewProducts_Result>("ViewProducts");
        }
    
        public virtual ObjectResult<ViewRetailers_Result> ViewRetailers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewRetailers_Result>("ViewRetailers");
        }
    
        public virtual ObjectResult<ViewUsers_Result> ViewUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewUsers_Result>("ViewUsers");
        }
    
        public virtual ObjectResult<ViewOrders_Result> ViewOrders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewOrders_Result>("ViewOrders");
        }
    }
}
